### ISSUE TITLE
Configuração do ARK FLOW

### ISSUE THREAD

**Issue by victormatteus04** [FlyingRobots-Pequi/uav_hardware#1]
Com a nova pixhawk 6x agora podemos utilizar também o sensor de fluxo óptico ARK FLOW. A ideia desse sensor é substituir a necessidade de utilização do GPS para obtenção de informação de posição. 

## Entregáveis

- [x] Configuração do sensor na nova pixhawk
- [x] Documentação dos parâmetros alterados na controladora
- [x] Documentação dos testes realizados(Gráficos, bags, vídeos)

## Responsáveis 

@gstvmt

**Comment by gstvmt** [comment]
A instalação do sensor foi bem sucedida.
Os parâmetros alterados para o funcionamento deste se encontram [aqui](https://github.com/Flying-Robots-2024/px4_params/blob/pix1_config/Parameters/params_config)
Os testes de verificação do funcionamento foram realizados por meio do MavLinkInspector no QGroundControl, porém ate o momento não foram documentados.
